---
title: "APICS"
author: "Thao Nguyen"
date: "2023-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r libraries loading}
library(tidyverse)
library(dplyr)
library(gtsummary)
library(ggplot2)
library(table1)
library(data.table)
library(writexl)
```

```{r files loading}
admission_file <- list.files(path = "C:/Thaontp/Thao/APICS/Data-analysis",
												pattern = "CoreForms.*.csv",
												recursive = TRUE)
admission <- do.call(rbind, lapply(admission_file, function(x) read.csv(x, stringsAsFactors = FALSE)))

daily_file <- list.files(path = "C:/Thaontp/Thao/APICS/Data-analysis",
									 pattern = "Daily.*.csv",
									 recursive = TRUE)

daily <- do.call(rbind, lapply(daily_file, function(x) read.csv(x, stringsAsFactors = FALSE)))

note_file <- list.files(path = "C:/Thaontp/Thao/APICS/Data-analysis",
												pattern = "Notes.*.csv",
												recursive = TRUE)
note <- do.call(rbind, lapply(note_file, function(x) read.csv(x, stringsAsFactors = FALSE)))

teadmission_file <- list.files(path = "C:/Thaontp/Thao/APICS/Data-analysis",
															 pattern = ".*Admission.*.csv",
															 recursive = TRUE)

teadmission <- do.call(rbind, lapply(teadmission_file, function(x) read.csv(x, stringsAsFactors = FALSE)))

tedischarge_files <- list.files(path = "C:/Thaontp/Thao/APICS/Data-analysis",
																pattern = ".*Discharge.*.csv",
																recursive = TRUE)

tedischarge <- do.call(rbind, lapply(tedischarge_files, function(x) read.csv(x, stringsAsFactors = FALSE)))

```

```{r clean}

teadmission <- teadmission %>% mutate_at(vars("date_of_admission", "date_of_admission_hospital"), ~as.Date(.))

teadmission <- teadmission %>% filter(date_of_admission >= "2021-01-01")

tedischarge <- tedischarge %>% filter(patient_id %in% teadmission$patient_id)

admission <- admission %>% mutate_at(vars("date_of_admission", "date_of_admission_hospital", "Discharge.date_of_discharge", "Discharge.date_of_hospital_discharge"), ~as.Date(.))

admission_date <- admission %>% 
	select(patient_id, date_of_admission)

admission <- admission %>% 
	filter(patient_id %in% teadmission$patient_id) %>% 
	select(patient_id, Admission.age, Admission.gender, Admission.fee_paying_method, Admission.comorbid_conditions, AdmissionAssessment.mechanically_ventilated, AdmissionAssessment.mechanically_ventilated_source, AdmissionAssessment.gcs_eye:AdmissionAssessment.gcs_motor, date_of_admission, date_of_admission_hospital, Discharge.date_of_discharge, Discharge.date_of_hospital_discharge, Discharge.discharge_status, AdmissionAssessment.antibiotics_pre_icu_admission, AdmissionAssessment.name_of_the_antibiotic:AdmissionAssessment.name_of_the_antibiotic_other, AdmissionAssessment.mechanically_ventilated, Discharge.cost_icu, Discharge.hospital_cost, Discharge.icu_cost, Discharge.hospital_discharge_status)

admission <- admission %>% 
	mutate_at(vars("AdmissionAssessment.name_of_the_antibiotic", "AdmissionAssessment.name_of_the_antibiotic2", "AdmissionAssessment.name_of_the_antibiotic3", "AdmissionAssessment.name_of_the_antibiotic4", "AdmissionAssessment.name_of_the_antibiotic5", "AdmissionAssessment.name_of_the_antibiotic_other"), ~ na_if(.,""))

upgrade <- tedischarge %>% select(patient_id, TetanusPreDischarge.mechanically_ventilated)

admission <- left_join(admission, upgrade, by = "patient_id")

admission <- admission %>% 
	mutate(Admission.comorbid_conditions = ifelse(Admission.comorbid_conditions == "None", "No", "Yes"),
				 icustay = as.numeric(Discharge.date_of_discharge - date_of_admission),
				 hosstay = as.numeric(Discharge.date_of_hospital_discharge - date_of_admission_hospital),
				 upgrade = ifelse(AdmissionAssessment.mechanically_ventilated == "self_vent" & TetanusPreDischarge.mechanically_ventilated == "mechanical_vent", "Yes", "No"),
				 Insurance = ifelse(Admission.fee_paying_method == "Self/out of pocket", "No", "Yes"))

admission <- admission %>% 
	mutate(antibiotics = rowSums(!is.na(select(., AdmissionAssessment.name_of_the_antibiotic: AdmissionAssessment.name_of_the_antibiotic_other))))

##GCS

admission <- admission %>% 
	mutate(eye = case_when(AdmissionAssessment.gcs_eye == "Eye opening spontaneously" ~ 4,
												 AdmissionAssessment.gcs_eye == "Eye opening to Speech" ~ 3,
												 AdmissionAssessment.gcs_eye == "Eye opening in response to pain" ~ 2,
												 TRUE ~ 1),
				 verbal = case_when(AdmissionAssessment.gcs_verbal == "Oriented" ~ 5,
				 									 AdmissionAssessment.gcs_verbal == "Confused" ~ 4,
				 									 AdmissionAssessment.gcs_verbal == "Inappropriate words" ~ 3,
				 									 AdmissionAssessment.gcs_verbal == "Incomprehensible sounds" ~ 2,
				 									 TRUE ~ 1),
				 motor = case_when(AdmissionAssessment.gcs_motor == "Obeys Commands" ~ 6,
				 									AdmissionAssessment.gcs_motor == "Locailzes to pain" ~ 5,
				 									AdmissionAssessment.gcs_motor == "Withdraws from pain" ~ 4,
				 									AdmissionAssessment.gcs_motor == "Flexion in response to pain" ~ 3,
				 									AdmissionAssessment.gcs_motor == "Extension to pain" ~ 2,
				 									TRUE ~ 1))

admission <- admission %>% mutate(gcs = eye + verbal + motor)

admission <- admission %>% 
	group_by(patient_id) %>% 
	mutate(Discharge.cost_icu = ifelse(is.na(Discharge.cost_icu), as.numeric(max(Discharge.hospital_cost, Discharge.icu_cost, na.rm = TRUE)), as.numeric(Discharge.cost_icu))) %>% 
	ungroup() %>% 
	select(-c(Admission.fee_paying_method, AdmissionAssessment.mechanically_ventilated, AdmissionAssessment.mechanically_ventilated_source:Discharge.date_of_hospital_discharge, starts_with("AdmissionAssessment.name_of_the_antibiotic"), Discharge.hospital_cost:TetanusPreDischarge.mechanically_ventilated, eye:motor))


tetanus <- teadmission %>% 
	select(patient_id, TetanusAdmission.ablett_score, TetanusAdmission.asa_score, TetanusAdmission.occupation, TetanusAdmission.address, TetanusAdmission.source_of_admission, TetanusAdmission.wound, TetanusAdmission.incubation_period, TetanusAdmission.time_period_from_1st_symptom_to_hospital_admis, TetanusAdmission.period_of_onset)

tetanus <- tetanus %>% mutate(Place = ifelse(str_detect(TetanusAdmission.address, regex("HCM|HCMC|Chi Minh|TPHCM", ignore_case = TRUE)) == TRUE, "HCM City", "Country side"),
															Occupation = ifelse(!TetanusAdmission.occupation %in% c("Farmer", "Worker", "Elderly"), "Other", TetanusAdmission.occupation),
															Ablett = case_when(TetanusAdmission.ablett_score %in% c("No spasm", "Spasm not interfering with respiration") ~ "Cluster 1",
																								 TRUE ~ "Cluster 2"),
															ASA = case_when(TetanusAdmission.asa_score == "Fit and well" ~ 1,
																							TetanusAdmission.asa_score == "Minor ilness or injury" ~ 2,
																							TetanusAdmission.asa_score == "Moderately severe disease" ~ 3,
																							TetanusAdmission.asa_score == "Severe illness not immediately life-threatening" ~ 4,
																							TRUE ~ 5),
															Timeonset = extract_numeric(TetanusAdmission.period_of_onset))

admission <- left_join(admission, tetanus, by = "patient_id")



##Predischarge

predischarge <- tedischarge %>% 
	select(patient_id, TetanusPreDischarge.start_date1, starts_with("TetanusPreDischarge.pre_discharge_complication")) %>% 
	left_join(admission_date, by = "patient_id") %>% 
	mutate(ANSD = rowSums(select(.,starts_with("TetanusPreDischarge.pre_discharge_complication")) == "Autonomic dysfunction"),
				 Sepsis = rowSums(select(.,starts_with("TetanusPreDischarge.pre_discharge_complication")) == "Sepsis"),
				 TetanusPreDischarge.start_date1 = as.Date(TetanusPreDischarge.start_date1),
				 Time_Ablett = as.numeric(TetanusPreDischarge.start_date1 - date_of_admission)) %>% 
	select(patient_id, ANSD, Sepsis, Time_Ablett)

predischarge <- predischarge %>% 
	mutate(ANSD = if_else(ANSD == 1, "Yes", "No", "No"),
				 Sepsis = if_else(Sepsis == 1, "Yes", "No", "No"))


##Daily

daily_dt <- daily %>% 
	filter(patient_id %in% teadmission$patient_id) %>% 
	select(patient_id, DailyAssessment.date_of_daily_assessment, DailyAssessment.mechanically_ventilated, DailyAssessment.urinary_catheterization, starts_with(c("DailyAssessment.infection", "DailyAssessment.source", "DailyAssessment.hos_acquired", "DailyAssessment.culture_report", "DailyAssessment.culture_date", "DailyAssessment.type_of_culture", "DailyAssessment.organism"))) %>% 
	left_join(admission_date, by= "patient_id")

##Count days

days_of_inter <- daily_dt %>% 
	arrange(patient_id, DailyAssessment.date_of_daily_assessment) %>% 
	group_by(patient_id) %>% 
	mutate(Ventday = sum(DailyAssessment.mechanically_ventilated %in% c("mechanical_vent")),
		Urinecath = sum(DailyAssessment.urinary_catheterization %in% c("Insitu", "New")),
				 Firsturine = ifelse(DailyAssessment.urinary_catheterization %in% c("Insitu", "New"), DailyAssessment.date_of_daily_assessment, NA),
				 Firsturine = as.Date(Firsturine[which.min(is.na(Firsturine))]),
				 Time_to_first_urine = as.numeric(Firsturine - date_of_admission)) %>% 
	ungroup() %>% 
	select(patient_id, Ventday, Urinecath, Time_to_first_urine) %>% 
	unique()

##Group deteriorate

admission_1 <- admission %>% mutate(upgrade = case_when(
	upgrade == "Yes" & Ablett == "Cluster 1" ~ "Deteriorate",
	upgrade == "Yes" & Ablett == "Cluster 2" ~ "Servere",
	upgrade == "No" & Ablett == "Cluster 1" ~ "Mild",
	upgrade == "No" & Ablett == "Cluster 2" ~ "Servere"))

admission_1 <- admission_1 %>% 
	left_join(predischarge, by = "patient_id")

admission_1 <- admission_1 %>% 
	left_join(days_of_inter, by = "patient_id")

##CAUTI

daily_dt <- daily_dt %>% 
	mutate_at(vars(starts_with("DailyAssessment.culture_date")), ~as.Date(.)) %>% 
	select(-c(DailyAssessment.mechanically_ventilated))


culture_long <- as.data.table(daily_dt) %>% 
	melt(measure = patterns("^DailyAssessment.infection","^DailyAssessment.source", 
                            "^DailyAssessment.hos_acquired",
                            "^DailyAssessment.culture_report", "^DailyAssessment.culture_date","^DailyAssessment.type_of_culture", "^DailyAssessment.organism"),
         value.name = c("DailyAssessment.infection","DailyAssessment.source", 
                        "DailyAssessment.hos_acquired",
                        "DailyAssessment.culture_report", "DailyAssessment.culture_date", "DailyAssessment.type_of_culture", "DailyAssessment.organism"))


culture_long <- culture_long %>% arrange(patient_id, DailyAssessment.date_of_daily_assessment) %>% group_by(patient_id)
	
insitu <- culture_long %>% 
	select(patient_id, patient_id:DailyAssessment.urinary_catheterization, DailyAssessment.infection:DailyAssessment.hos_acquired) %>% 
	unique()

insitu[insitu == ""] <- NA

insitu <- unique(insitu)

insitu <- insitu %>% 
	mutate(clinical = ifelse((!is.na(DailyAssessment.infection) & DailyAssessment.source == "Urinary System Infection"), "Yes", "No"))

insitu <- insitu %>% 
	select(patient_id, DailyAssessment.date_of_daily_assessment, DailyAssessment.urinary_catheterization, clinical) %>% 
	unique()

insitu <- insitu %>% 
	mutate(DailyAssessment.urinary_catheterization = ifelse(DailyAssessment.urinary_catheterization == "No", 0L, 1L),
				 clinical = ifelse(clinical == "No", 0L, 1L)) %>% 
	arrange(patient_id, DailyAssessment.date_of_daily_assessment) %>% 
	group_by(patient_id, DailyAssessment.date_of_daily_assessment) %>% 
	filter(DailyAssessment.urinary_catheterization == max(DailyAssessment.urinary_catheterization),
				 clinical == max(clinical)) %>% 
	ungroup()

insitu <- insitu %>%
	group_by(patient_id) %>% 
	mutate(CAUTIclinical = ifelse(clinical == 1L & ((DailyAssessment.urinary_catheterization == 1L & lag(DailyAssessment.urinary_catheterization) == 1L & lag(lag(DailyAssessment.urinary_catheterization)) == 1L) | (DailyAssessment.urinary_catheterization == 0L & lag(lag(DailyAssessment.urinary_catheterization == 1L)))), "Yes", "No"))

##Clinical CAUTI

clinicalCAUTI <- insitu %>% 
	select(patient_id, CAUTIclinical) %>% 
	filter(CAUTIclinical == "Yes") %>% 
	filter(!duplicated(patient_id))

daily_date <- insitu %>% 
	select(patient_id, DailyAssessment.date_of_daily_assessment, DailyAssessment.urinary_catheterization)

daily_date$DailyAssessment.date_of_daily_assessment <- as.Date(daily_date$DailyAssessment.date_of_daily_assessment)


culture_date <- culture_long %>% 
	select(patient_id, DailyAssessment.culture_report:DailyAssessment.organism)

daily_date <- left_join(daily_date, culture_date, by = c("patient_id", "DailyAssessment.date_of_daily_assessment" = "DailyAssessment.culture_date"))

daily_date <- daily_date %>% 
	mutate(CAUTI_CDC = ifelse(DailyAssessment.urinary_catheterization == 1L & DailyAssessment.culture_report == "Growth" & DailyAssessment.type_of_culture == "Urine", "Yes", "No"))

library(writexl)

cdcCAUTI <- daily_date %>% 
	select(patient_id, CAUTI_CDC) %>% 
	filter(CAUTI_CDC == "Yes") %>% 
	filter(!duplicated(patient_id))

#write_xlsx(clinicalCAUTI, "Clinical CAUTI.xlsx")
#write_xlsx(cdcCAUTI, "CDC CAUTI.xlsx")
## CAUTI-CDC

catheter <- daily %>% 
	filter(patient_id %in% teadmission$patient_id) %>% 
	select(patient_id, DailyAssessment.date_of_daily_assessment, DailyAssessment.urinary_catheterization) %>% 
	arrange(patient_id, DailyAssessment.date_of_daily_assessment) %>% 
	group_by(patient_id) %>% 
	mutate(DailyAssessment.urinary_catheterization = ifelse(DailyAssessment.urinary_catheterization %in% c("New", "Insitu"), 1L, 0L)) %>% 
	filter(DailyAssessment.urinary_catheterization == 1L) %>% 
	unique()

patient_cath <- catheter[!duplicated(catheter$patient_id),]

patient_cath <- patient_cath %>% 
	select(patient_id, DailyAssessment.urinary_catheterization)

cathdays <- catheter %>% 
	summarise(n = n())

admission_1 <- admission_1 %>% 
	left_join(clinicalCAUTI, by = "patient_id") %>% 
	left_join(cdcCAUTI, by = "patient_id")

admission_1 <- admission_1 %>% 
	left_join(patient_cath, by = "patient_id")

admission_1 <- admission_1 %>% 
	mutate(CAUTIclinical = ifelse(is.na(CAUTIclinical), "No", "Yes"), 
				 CAUTI_CDC = ifelse(is.na(CAUTI_CDC), "No", "Yes"),
				 DailyAssessment.urinary_catheterization = ifelse(is.na(DailyAssessment.urinary_catheterization), "No", "Yes"))


##Table
admission %>% select(-c(patient_id, TetanusAdmission.ablett_score:TetanusAdmission.address, TetanusAdmission.period_of_onset)) %>% tbl_summary(by = Ablett, statistic = list(all_continuous() ~ "{median} ({p25}, {p75})", all_categorical() ~ "{n} / {N} ({p}%)"
    ), label = c(Admission.age ~ "Age", Admission.gender ~ "Gender", TetanusAdmission.time_period_from_1st_symptom_to_hospital_admis ~ "First symptom to admission")) %>% add_p()


subdata <- admission_1 %>% 
	select(upgrade, CAUTIclinical, CAUTI_CDC, DailyAssessment.urinary_catheterization) %>% 
	filter(DailyAssessment.urinary_catheterization == "Yes")

tbl_summary(subdata, by = upgrade, statistic = list(all_continuous() ~ "{median} ({p25}, {p75})", all_categorical() ~ "{n} / {N} ({p}%)")) %>% add_p()

subdata_count <- admission_1 %>% 
	select(patient_id, upgrade, DailyAssessment.urinary_catheterization, CAUTI_CDC) %>% 
	filter(DailyAssessment.urinary_catheterization == "Yes")

subdata_count <- subdata_count %>% 
	left_join(cathdays, by = "patient_id")

subdata_count %>% select(upgrade, n) %>% tbl_summary(by = "upgrade", label = c(n ~ "Length of catheter")) %>% add_p()

##Customize for tbl_summary

#my_stats <- function(data, ...) {
#  cluster1_sum <- sum(data$n[data$Ablett == "Cluster 1"], na.rm = TRUE)
#  cluster2_sum <- sum(data$n[data$Ablett == "Cluster 2"], na.rm = TRUE)
#  dplyr::tibble(
#    cluster1_sum = cluster1_sum,
#    cluster2_sum = cluster2_sum
#  )
#}

library(data.table)

tb <- subdata_count %>% 
	group_by(upgrade, CAUTI_CDC) %>% 
	summarise(cauti = sum(n)) %>% 
	ungroup() %>% 
	pivot_wider(names_from = CAUTI_CDC,
							values_from = cauti)

tb <- tb %>% mutate(sum = rowSums(select(., c("No", "Yes"))))

tb1 <- table(subdata_count$upgrade, subdata_count$CAUTI_CDC) %>% 
	as.data.frame() %>% 
	filter(Var2 == "Yes")

tb <- left_join(tb, tb1, by = c("upgrade" = "Var1"))

tb <- tb %>% mutate(divide = (Freq/sum)*1000)

tb %>% select(upgrade, divide) %>% tbl_summary(by = "upgrade", type = list(divide ~ 'continuous'), statistic = list(all_continuous() ~ "{mean}")) %>% add_p()
##Re-make

vent <- admission_1 %>% 
	select(patient_id, upgrade, Timeonset, Ventday)

vent <- vent %>% mutate(Timeonset = case_when(Timeonset %in% c(24, 48) ~ "24-48h",
																							Timeonset %in% c(72, 96) ~ "72-96h",
																							Timeonset %in% c(120) ~ ">96h",
																							TRUE ~ "Missing"))

vent %>% select(upgrade, Timeonset) %>% tbl_summary(by = "upgrade") %>% add_p()

mecha <- vent %>% filter(Ventday != 0) %>% select(upgrade, Ventday) %>% tbl_summary(by = "upgrade") %>% add_p()

```

```{r}
##Time of retaining urine catheter

retain <- daily_dt %>% 
	select(patient_id:DailyAssessment.urinary_catheterization) %>% 
	filter(DailyAssessment.urinary_catheterization != "No") %>% 
	arrange(patient_id, DailyAssessment.date_of_daily_assessment) %>% 
	group_by(patient_id) %>% 
	mutate(DailyAssessment.urinary_catheterization = ifelse(DailyAssessment.urinary_catheterization == "No", NA, "Yes")) %>% 
	unique() %>% 
	ungroup()


retain1 <- transform(retain, Counter = ave(DailyAssessment.urinary_catheterization, rleid(patient_id, DailyAssessment.urinary_catheterization), FUN = seq_along))

retain1$DailyAssessment.date_of_daily_assessment <- as.Date(retain1$DailyAssessment.date_of_daily_assessment)

retain1 <- retain1 %>% group_by(patient_id) %>% mutate(countday = cumsum(c(1, diff(DailyAssessment.date_of_daily_assessment) > 1)))

retain1 <- retain1 %>% select(patient_id, Counter, countday) %>% group_by(patient_id, countday) %>% mutate(length = max(Counter)) %>% select(-Counter) %>% unique() 

```

```{r}
ablett <- subdata_count %>%
	mutate(length = case_when(n <= 5 ~ "1-5 Days",
				 									 n > 5 & n < 10 ~ "6-10 Days",
				 									 TRUE ~ "> 10 Days"))

subset <- admission_1 %>% 
	select(patient_id, Time_to_first_urine, CAUTIclinical)

ablett <- ablett %>% left_join(subset, by="patient_id")


ablett %>% select(-c(patient_id, DailyAssessment.urinary_catheterization)) %>%  tbl_summary(by = "upgrade", label = c(n ~ "Length of catheter", length ~ "Group of catheter length")) %>% add_p()

admission_1 <- admission_1 %>% mutate(Discharge.cost_icu = as.numeric(round(Discharge.cost_icu/23493, 2)))

admission_1 %>% select(Ventday, ANSD, Sepsis, Discharge.cost_icu:upgrade) %>% tbl_summary(by = "upgrade") %>% add_p()
```

```{r}
group <- admission_1 %>% select(patient_id, Urinecath, CAUTI_CDC)

group_new <- admission_1 %>% select(patient_id, upgrade)

cath_new <- left_join(group_new, subdata_count, by = c("patient_id", "upgrade")) %>% 
	mutate(DailyAssessment.urinary_catheterization = replace_na(DailyAssessment.urinary_catheterization, "No"))

cath_new %>% select(upgrade, DailyAssessment.urinary_catheterization) %>% tbl_summary(by = upgrade) %>% add_p()
```

```{r, eval=FALSE}

frequen_anti <- daily %>% 
	filter(patient_id %in% teadmission$patient_id) %>% 
	select(patient_id,DailyAssessment.date_of_daily_assessment, starts_with(c("DailyAssessment.name_of_the_antibiotic")))

frequen_anti <- as.data.table(frequen_anti) %>% melt(measure = patterns("^DailyAssessment.name_of_the_antibiotic"),
																										 value.name = "Antibiotics") %>% 
	select(-variable) %>% 
	filter(!Antibiotics %in% c("", "Metronidazole(Flagyl)")) %>% 
	unique()

frequen_anti <- frequen_anti %>% filter(!is.na(Antibiotics))

frequen_anti <- frequen_anti %>% 
	arrange(patient_id, DailyAssessment.date_of_daily_assessment)

frequen_anti <- left_join(frequen_anti, insitu, by = c("patient_id", "DailyAssessment.date_of_daily_assessment"))

frequen_anti <- frequen_anti %>% 
	group_by(patient_id, DailyAssessment.date_of_daily_assessment) %>% 
	ungroup() %>% 
	select(-c(DailyAssessment.urinary_catheterization, DailyAssessment.date_of_daily_assessment, clinical)) %>% 
	unique() 

##Pick antibiotics when CAUTI occurs
frequen_anti <- frequen_anti %>% 
	filter(CAUTIclinical == "Yes")


##

library(janitor)

anti_use <- tabyl(frequen_anti$Antibiotics, sort = TRUE) %>% 
	arrange(desc(n)) %>% 
	mutate(percent = round(percent*100, 2))

colnames(anti_use) = c("Antibiotics names", "Frequency", "Percentage")


##Organism

micro <- daily_date %>% 
	select(patient_id, DailyAssessment.type_of_culture, DailyAssessment.organism) %>% 
	left_join(cdcCAUTI, by = "patient_id") %>% 
	filter(!is.na(CAUTI_CDC) & DailyAssessment.type_of_culture == "Urine" & DailyAssessment.organism != "") %>% 
	unique()

micro_culture <- tabyl(micro$DailyAssessment.organism, sort = TRUE) %>% 
	arrange(desc(n)) %>% 
	mutate(percent = round(percent*100, 2))

colnames(micro_culture) = c("Organism names", "Frequency", "Percentage")

library(writexl)

#write_xlsx(anti_use, "Antibiotics use in Clinical CAUTI.xlsx")

#write_xlsx(micro_culture, "Microbes culture in CDC CAUTI.xlsx")
```

```{r, eval=FALSE}

##Sites separated

anti_group <- select(admission, patient_id, Ablett)

site_anti_use <- inner_join(frequen_anti, sitepatient, by = "patient_id")

site_anti <- ungroup(site_anti_use) %>% 
	select(DailyAssessment.name_of_the_antibiotic, Site) %>% 
	filter(DailyAssessment.name_of_the_antibiotic %in% anti_use$`Antibiotics names`) %>% tbl_summary(by = Site, sort = all_categorical() ~ "frequency", label = DailyAssessment.name_of_the_antibiotic ~ "Antibiotics name") %>% 
	as_gt() %>% 
	opt_table_font(font = list("Serif"))%>%
  tab_options(table.font.size = px(11L))

site_anti
##graph

cbPalette <- c("#66347F", "#C92C6D", "#D27685", "#BFACE2", "#3E54AC", "#E7B10A", "#0E8388")

antibiotic_site <- select(site_anti_use, patient_id, DailyAssessment.name_of_the_antibiotic, Site) %>% 
	filter(DailyAssessment.name_of_the_antibiotic %in% anti_use$`Antibiotics names`) %>% group_by(patient_id, DailyAssessment.name_of_the_antibiotic)

graphanti <- ggplot(antibiotic_site, aes(y = forcats::fct_rev(forcats::fct_infreq(DailyAssessment.name_of_the_antibiotic)), fill = Site)) +
  geom_bar() + 
	theme_classic() + 
	labs(title = "Common antibiotics used in ICUs", x = "", y = "") + scale_fill_manual(values=cbPalette) + 
	theme(
    axis.text.y = element_text(size = 5, face = "bold"),
    axis.text.x = element_text(size = 7, face = "bold"),
    plot.title = element_text(hjust = 0.1, face = "bold", size = 7),
    legend.title= element_blank(),
    legend.text = element_text(size = 7, face = "bold"),
    legend.key.size = unit(0.6, 'cm'))

#write_xlsx(admission, "Admission.xlsx")
```

